### ISSUE TITLE
[TEST - FRONT] No mezclar idiomas en el código

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#1]
- Escribir todo el código en un único idioma (inglés). 
(Excepto palabras o frases que tengan que aparecer en el front en otro idioma).

![imagen](https://user-images.githubusercontent.com/9888356/191009585-64c333ad-16ec-4e2e-b2c9-d2852b11e62a.png)

**Comment by guillermoVicenteGonzalez** [comment]
hecho

**Comment by Galazord** [comment]
Por parte del código bien, pero en el front elige si lo muestras todo en español o en inglés.
![imagen](https://user-images.githubusercontent.com/9888356/191480823-a5f192a7-307e-4556-a360-f7943cbd2048.png)

**Comment by guillermoVicenteGonzalez** [comment]
hecho
