### ISSUE TITLE
[TEST - FRONT] Ocultar funcionalidades que no se usen.

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#10]
- Elimina u oculta (si tienes pensado hacerlo más adelante) todas aquellas funcionalidades que no funcionan en ese momento.
Por ejemplo el caso del icono de menú lateral, que a parte de no funcionar no sirve ahora para nada.

Si hay algo que quieras mantener por cualqueir motivo y tiene un botón o una acción que no hace nada, al menos saca un modal al pulsarlo en plan "Esta función no está disponible en este momento" o algo similar.

**Comment by Galazord** [comment]
Mira a ver que haces con el footer ;)

**Comment by guillermoVicenteGonzalez** [comment]
hecho??
