### ISSUE TITLE
[TEST - FRONT] Crear un fichero de variables globales

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#2]
- Las rutas o variables que vayan a ser fijas o globales no las repitas en cada fichero que las necesites.
- En su lugar crea un config.json dentro de src e importas ese archivo donde lo necesites. 

![imagen](https://user-images.githubusercontent.com/9888356/191011181-a6e03db6-414d-466e-8436-33e02e3d1301.png)

NOTA: en el caso de las rutas no las pongas enteras. Ejemplo:
{
    "host": "http://localhost:9999",
    "apiUrl": "/nombreProyecto/api/v1",
    "register": "/users/register"
}

**Comment by guillermoVicenteGonzalez** [comment]
hecho
