### ISSUE TITLE
[TEST - FRONT] Aplicar algo de diseño

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#20]
Por lo menos aplica algo de color  (que está muy triste la página sólo a blanco y negro) que también te va a ayudar a ti a programar mejor viendo como va tomando todo forma ;)
No te preocupes si no sabes qué color va mejor y cómo se colocan los elementos. Todos hemos pasado por eso. Tan sólo prueba algo y experimenta un poco. Si te ves con dificultades me preguntas cualquier cosa.
Por ejemplo, la ventana modal que has creado mejoraría mucho si pusieras tan sólo el texto de "Éxito" en verde claro, centraras el texto y si le incluyes un icono de check o de que se ha hecho correctamente y verás que, con tan poco, avanzas mucho.
![imagen](https://user-images.githubusercontent.com/9888356/191482956-d290824f-1b6e-46ae-8313-569a2ffc086f.png)

**Comment by Galazord** [comment]
Por lo menos ya hay algo de color. No obstante centra el panel del login.
Cuando termines te enseñaré alguna página de las que yo hago para que veas ejemplos de diseño ;)

**Comment by guillermoVicenteGonzalez** [comment]
hecho
