### ISSUE TITLE
[TEST - FRONT] Actualizar gráficos cuando el usuario haga login

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#21]
Si al hacer el login, el usuario introduce correctamente sus datos, oculta las opciones de los dos botones de "Sign in" y de "Sign Up" y los sustituyes todo por un icono de usuario junto con el nombre del usuario logado y otro icono a la derecha del todo que represente cerrar sesión (y si lo pulsas se cierra sesión y se restauran los dos botones).

**Comment by guillermoVicenteGonzalez** [comment]
hecho

**Comment by Galazord** [comment]
- El registro lo hace bien pero en vez de salir un modal de correcto sale de incorrecto (pruébalo).
- Al cerrar sesión incorpora siempre un modal de si está seguro de hacerlo para evitar que pulse por error.
- Busca una forma para evitar que al refrescar la página se pierda el login.

**Comment by guillermoVicenteGonzalez** [comment]
hecho
