### ISSUE TITLE
[TEST - IMPORTANTE] Subir el gitignore

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#29]
- Cuando subas una rama o hagas un commit asegurate de que se sube un fichero llamado .gitignore que se encuentra a la altura del index.html.
Si no lo subes ocurren cosas graves como que la carpeta del node_modules se sube a github y ocupa una salvajada el proyecto (y un dolor y una paciencia para cuando se lo descargue alguien).

**Comment by guillermoVicenteGonzalez** [comment]
hecho

**Comment by Galazord** [comment]
La colocación del gitignore es correcta.
Te falta eliminar el node_modules del repositorio del github.
Esta vez te mando los comandos para que lo hagas de la forma correcta siempre.
Situate en la carpeta front y ejecuta:

```
git rm -rf node_modules
git add .
git commit -m "Deleted node_modules"
git push origin main
```

**Comment by guillermoVicenteGonzalez** [comment]
hecho
