### ISSUE TITLE
[TEST - FRONT] Explicar el error en cada modal.

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#32]
- Cuando intento dar de alta un usuario sin rellenar el campo del usuario o el de la contraseña, salta un modal de error (por esa parte bien) pero en estos casos especifica el por qué. Es decir, mustra algo como "Rellena todos los campos" o "Introduce primero el nombre de usuario".

NOTA: Puede ser que en algún caso sea correcto registrar un usuario sin contraseña. Este proyecto como es de prueba para ti te lo dejo a tu elección hacerlo. En caso de dejar la posibilidad de registrar sin contraseña, añade un modal antes avisando de que va a guardar con una contraseña vacía.

**Comment by guillermoVicenteGonzalez** [comment]
hecho
