### ISSUE TITLE
[TEST- API] No usar 409

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#33]
En el caso de usersCtrl no uses una respuesta de 409 sino de 400. Ya que el primero no puedes mandarle un contenido y al usar el método JSON le estás diciendo que ponga la cabecera content-type el contenido application/json después de mandarse la petición por lo que genera el error:
![imagen](https://user-images.githubusercontent.com/9888356/192730376-fb5c98b2-1926-4956-818d-de917197e48c.png)
Que hace que el servidor se cierre debido al error.

**Comment by guillermoVicenteGonzalez** [comment]
hecho
