### ISSUE TITLE
[TEST - FRONT] Organizar los assets en carpetas

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#5]
- A modo de que todo quede mejor estructurado de cara a cuando el proyecto sea más grande, crea carpetas en el assets para cada recurso.
Es decir, una para los estilos (styles), otra para imágenes (img), etc.
Y no crees dos ficheros de css. Crea uno para todo.

![imagen](https://user-images.githubusercontent.com/9888356/191013862-1e661296-b662-4dac-8fbf-835b7ee610f4.png)

**Comment by guillermoVicenteGonzalez** [comment]
hecho
