### ISSUE TITLE
[TEST - API] Mejorar la descripción del Swagger

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#6]
- En la documentación del Swagger se debe mostrar como en este ejemplo que te muestro:

![imagen](https://user-images.githubusercontent.com/9888356/191014319-06e1782b-53dc-421b-925b-4812b89621be.png)

Para ello mírate esta página: https://www.npmjs.com/package/express-swagger-generator
En esta parte que dice:
/**
 * Adds the described slaughterhouse to the user
 * @route POST /slaughterhouses
 * @group Slaughterhouses
 * @param {Slaughterhouse.model} body.body.required - The slaughtehouse's to be added data
 * @returns {Slaughterhouse.model} 201 - The slaughterhouse has been created correctly
 * @returns {object} 400 - Bad request
 * @returns {object} 401 - Unauthorized
 * @security JWT
 */

El body tiene que indicarse de esta manera habiendo definido el model así:

/**
 * @typedef Slaughterhouse
 * @property {string} id.required - Slaughterhouse identifier
 * @property {string} name.required - Name of the slaughterhouse
 * @property {object} location - Slaughterhouse's location
 * @property {Array<string>} cows - References to the cows that has been sacrificed in the slaughterhouse
 */

**Comment by guillermoVicenteGonzalez** [comment]
hecho
