### ISSUE TITLE
[TEST - FRONT] Los iconos dentro de Assets

### ISSUE THREAD

**Issue by Galazord** [guillermoVicenteGonzalez/prototypeApp#7]
- Los recursos de iconos mételos en un carpeta que ponga "icons" o "ic" dentro de Assets. Nunca dentro de components.

NOTA: Vue y sobretodo Vuetify tienen ya una lista de iconos amplia sin tener que almacenarlos en local. Sólamente añade los iconos que hayas creado tu mismo o personalices.
Mírate: 
https://vuetifyjs.com/en/components/icons/

https://materialdesignicons.com/

**Comment by guillermoVicenteGonzalez** [comment]
hecho

**Comment by Galazord** [comment]
Los iconos no son imágenes (img). Crea otra carpeta llamada icons.
O más bien si esos iconos no se usan en ningún lado eliminalos para que no ocupen espacio (creo que todos los que tienes son los generados automáticamente por vue).

Resumen: 
En img van los .jpeg, .png, etc
En icons pueden ir .png pero se recomienda siempre mejor en .svg (logos incluidos).

**Comment by guillermoVicenteGonzalez** [comment]
¿Los dos iconos que hay en public deben ir también a assets/icons o deben quedarse donde están?

**Comment by Galazord** [comment]
el de ancla no porque se usa para la pestaña (y al estar fuera de la estructura de vue no está mal dejarlo ahi).
El favicon.ico ese lo puedes eliminar porque es el de por defecto y cuanta menos "basurilla" por el código y las carpetas siempre será más óptimo.

**Comment by guillermoVicenteGonzalez** [comment]
hecho
